# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: "Setup Node + Install"
description: "Set up Node v18, and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm ci
      shell: bash