on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/setup-node
      - run: npm run build
        shell: bash