name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - name: Common Setup
        uses: ./.github/actions/setup-node
      - name: Run vitest
        run: npm run test -- --coverage

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - name: Common Setup
        uses: ./.github/actions/setup-node
      - name: Check format
        run: npm run format:check
      - name: Perform linting
        run: npm run lint -- --max-warnings=0